services:
    ite.mail.manager:
        class: ITE\MailBundle\Manager\MailManager
        arguments: [ @service_container ]

    ite.mail.token_manager:
        class: ITE\MailBundle\Manager\TokenManager
        arguments: [@assetic.asset_factory]
        tags:
            - {name: kernel.event_listener, event: ite.mail, method: onMail}

#Example add extension
#    jroc.mail.token.main_extension:
#        class: Jroc\CoreBundle\Manager\Mail\MainExtension
#        arguments: [@service_container]
#        tags:
#            - {name: jroc.mail.token_extension}